version: '{build}'
image: Visual Studio 2019 Preview
configuration: Debug
skip_branch_with_pr: true
before_build:
- choco install codecov
- choco install dotnetcore-sdk --pre
build_script:
- dotnet pack -c Release
test_script:
- dotnet test -c Release .\test\UnitTests\
- codecov -f coverage.xml
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
  - path: '**\*.snupkg'
    name: NuGet Symbol Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    appveyor_repo_tag: true